#!/usr/bin/env python3
"""Generate LaTeX tables from paper evaluation CSVs."""
from __future__ import annotations

import csv
from pathlib import Path

from _common import DATA_DIR, TABLES_DIR, ensure_dirs


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    lines = [ln for ln in path.read_text(encoding="utf-8").splitlines() if not ln.startswith("#")]
    if len(lines) < 2:
        return []
    return list(csv.DictReader(lines))


def esc(s: str) -> str:
    return (
        str(s)
        .replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
    )


def map_arm_name(name: str) -> str:
    mapping = {
        "B1_Bloat": r"$B_{FC}$ (Full-Context Bloat)",
        "B3_Baseline": r"$B_{RP}$ (Retrieve-and-Prefill)",
        "Nexus_Production": "Nexus Production Gateway"
    }
    return mapping.get(name, esc(name))


def map_config_name(name: str) -> str:
    mapping = {
        "Nexus_Dense_Only": "Dense Only",
        "Nexus_v0_Uncalibrated": "v0 Uncalibrated",
        "Nexus_v1_Production": "v1 Production"
    }
    return mapping.get(name, esc(name))


def main() -> int:
    ensure_dirs()
    TABLES_DIR.mkdir(parents=True, exist_ok=True)

    parts: list[str] = [
        "% Auto-generated by docs/paper/scripts/generate_latex_tables.py",
        "% Requires: \\usepackage{booktabs}",
        "",
    ]

    # Table I: E2E macro
    pareto = read_csv(DATA_DIR / "pareto_frontier.csv")
    if pareto:
        parts += [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{End-to-end latency and tool-hit accuracy (n=100 hold-out).}",
            "\\label{tab:e2e-macro}",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Configuration & Acc. & TTFT P50 & P90 & P99 \\\\",
            "\\midrule",
        ]
        for r in pareto:
            parts.append(
                f"{map_arm_name(r['arm'])} & {r['tool_hit_accuracy']} & "
                f"{r['ttft_p50_ms']} & {r['ttft_p90_ms']} & {r['ttft_p99_ms']} \\\\"
            )
        parts += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    # Table II: ML ablation
    ablation = read_csv(DATA_DIR / "ml_ablation_table.csv")
    if ablation:
        parts += [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{ML routing ablation on 100-query hold-out.}",
            "\\label{tab:ml-ablation}",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Configuration & Accuracy & TTFT P50 & CE Rate \\\\",
            "\\midrule",
        ]
        for r in ablation:
            cfg = map_config_name(r['config'])
            acc = f"{float(r['tool_hit_accuracy']):.2f}"
            ttft = f"{float(r['ttft_p50_ms']):.1f} ms"
            ce_rate = f"{float(r['ce_invocation_rate']) * 100:.0f}\\%"
            parts.append(
                f"{cfg} & {acc} & {ttft} & {ce_rate} \\\\"
            )
        parts += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    # Table III: Scalability
    scale = read_csv(DATA_DIR / "scalability_curve.csv")
    if scale:
        parts += [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Registry scalability: SLB scan latency and memory footprint.}",
            "\\label{tab:scalability}",
            "\\begin{tabular}{rrrrr}",
            "\\toprule",
            "$N$ & SLB P50 ($\\mu$s) & SLB P99 ($\\mu$s) & Mem (MB) & E2E P50 (ms) \\\\",
            "\\midrule",
        ]
        for r in scale:
            parts.append(
                f"{r['n_tools']} & {r['slb_scan_p50_us']} & {r['slb_scan_p99_us']} & "
                f"{r['memory_mb']} & {r['e2e_ttft_p50_ms']} \\\\"
            )
        parts += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    # Table IV: Physics boundary
    physics = read_csv(DATA_DIR / "physics_boundary_rope.csv")
    if physics:
        parts += [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{RoPE physics boundary: KL divergence vs.\\ context depth $P$.}",
            "\\label{tab:physics}",
            "\\begin{tabular}{rrlrr}",
            "\\toprule",
            "$P$ & Suffix\\% & Strategy & KL (nats) & Top-1 \\\\",
            "\\midrule",
        ]
        for r in physics:
            parts.append(
                f"{r['P']} & {r['suffix_pct']} & {esc(r['strategy'])} & "
                f"{r['kl_mean_nats']} & {r['top1_agreement']} \\\\"
            )
        parts += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    # Table V: L0 radix
    l0 = read_csv(DATA_DIR / "l0_radix_metrics.csv")
    if l0:
        parts += [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{L0 exact-token radix microbenchmark.}",
            "\\label{tab:l0-radix}",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Mode & Hit Rate (\\%) & Frag. (\\%) & Copy P50 ($\\mu$s) & Copy P99 ($\\mu$s) \\\\",
            "\\midrule",
        ]
        for r in l0:
            p50 = r.get("copy_p50_us", "---") or "---"
            p99 = r.get("copy_p99_us", "---") or "---"
            parts.append(
                f"{esc(r['mode'])} & {r['hit_rate_pct']} & {r['fragmentation_pct']} & "
                f"{p50} & {p99} \\\\"
            )
        parts += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    out = TABLES_DIR / "PAPER_TABLES.tex"
    out.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
