#!/usr/bin/env python3
"""Calibrate margin thresholds on synthetic queries; emit src/nexus_calibration.py."""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "test"))
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "build"))
sys.path.insert(0, str(ROOT / "scripts"))

lib_dir = ROOT / "build/external/llama.cpp/src"
os.environ["LLAMA_CPP_LIB_PATH"] = str(lib_dir)
os.environ["LLAMA_CPP_LIB"] = str(lib_dir / "libllama.dylib")

import llama_cpp  # noqa: E402
from bench_routing_accuracy import load_first_10_tools  # noqa: E402
from nexus_retrieval import (  # noqa: E402
    DEFAULT_EMBED_MODEL,
    HARD_NEGATIVE_TUPLES,
    _topk_tool_name,
    dense_margin,
    embed_query,
    embed_tools,
    margin_percentile_threshold,
    retrieve_hybrid,
)
from synthetic_ce_training_data import all_synthetic_queries  # noqa: E402

DEFAULT_OUTPUT_PY = ROOT / "src/nexus_calibration.py"
DEFAULT_AUDIT_JSON = ROOT / "results/margin_calibration_p20.json"
AMBIGUOUS_CLAMP_FLOOR = 0.15


def _is_hard_negative_topk(topk: list) -> bool:
    if len(topk) < 2:
        return False
    name1 = _topk_tool_name(topk[0])
    name2 = _topk_tool_name(topk[1])
    return tuple(sorted([name1, name2])) in HARD_NEGATIVE_TUPLES


def write_calibration_py(
    path: Path,
    *,
    base_threshold: float,
    ambiguous_threshold: float,
    meta: dict,
) -> None:
    path.write_text(
        f"""# AUTO-GENERATED BY scripts/calibrate_margin_threshold.py — DO NOT EDIT
CALIBRATED_MARGIN_THRESHOLD = {base_threshold!r}
CALIBRATED_AMBIGUOUS_MARGIN = {ambiguous_threshold!r}
CALIBRATION_META = {json.dumps(meta, indent=4)}
"""
    )


def main() -> int:
    p = argparse.ArgumentParser(description="Calibrate margin gate on synthetic queries only.")
    p.add_argument("--embed-model", default=DEFAULT_EMBED_MODEL)
    p.add_argument("--output-py", default=str(DEFAULT_OUTPUT_PY))
    p.add_argument("--audit-json", default=str(DEFAULT_AUDIT_JSON))
    args = p.parse_args()

    tools = load_first_10_tools()
    tool_names = [t["name"] for t in tools]
    cases = all_synthetic_queries(tools)

    llm_emb = llama_cpp.Llama(model_path=args.embed_model, embedding=True, verbose=False)
    tool_embs, _ = embed_tools(llm_emb, tools)

    all_margins: list[float] = []
    adversarial_margins: list[float] = []
    hard_margins: list[float] = []
    per_query: list[dict] = []

    for case in cases:
        q = case["query"]
        q_emb = embed_query(llm_emb, q)
        margin = dense_margin(q_emb, tool_embs)
        topk = retrieve_hybrid(q, q_emb, tool_embs, tool_names, tools, 5)
        all_margins.append(margin)
        if case.get("hard"):
            adversarial_margins.append(margin)
        if _is_hard_negative_topk(topk):
            hard_margins.append(margin)
        per_query.append({
            "query": q,
            "gold": case.get("gold"),
            "margin": margin,
            "top5": topk[:5],
            "hard_pair_top2": _is_hard_negative_topk(topk),
            "adversarial": bool(case.get("hard")),
        })

    p20_all = margin_percentile_threshold(all_margins, 20)
    p20_adversarial = (
        margin_percentile_threshold(adversarial_margins, 20)
        if adversarial_margins
        else p20_all
    )
    base_thr = float(p20_adversarial["threshold"])

    # Static 0.15 clamp per M3 directive (stored for audit; routing uses base P20 gate).
    ambig_thr = AMBIGUOUS_CLAMP_FLOOR

    meta = {
        "n_synthetic_queries": len(cases),
        "n_adversarial_queries": len(adversarial_margins),
        "n_hard_pair_top2_queries": len(hard_margins),
        "p20_all_fire_rate": p20_all["fire_rate"],
        "p20_adversarial_fire_rate": p20_adversarial["fire_rate"],
        "p20_all_threshold": p20_all["threshold"],
        "hard_margin_max": max(hard_margins) if hard_margins else None,
        "ambiguous_method": "static_0.15_clamp",
        "base_threshold_source": "p20_adversarial_synthetic_query_margins",
    }

    out_py = Path(args.output_py)
    write_calibration_py(out_py, base_threshold=base_thr, ambiguous_threshold=ambig_thr, meta=meta)

    audit = {
        "calibration": {
            "CALIBRATED_MARGIN_THRESHOLD": base_thr,
            "CALIBRATED_AMBIGUOUS_MARGIN": ambig_thr,
        },
        "p20": p20_all,
        "p20_adversarial": p20_adversarial,
        "meta": meta,
        "per_query": per_query,
    }
    audit_path = Path(args.audit_json)
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit_path.write_text(json.dumps(audit, indent=2) + "\n")

    print(json.dumps({"written": str(out_py), **audit["calibration"], "meta": meta}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
